### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by jamesarosen** [alrra/travis-after-all#14]
I'm trying to use the JavaScript interface to travis-after-all and I'm getting the following on every build:
```
[travis-after-all] Job succeeded (a0d...)
[travis-after-all] Failed to parse JSON from "https://api.travis-ci.org/builds/195...".
Error: Unexpected end of input
Failed to parse JSON from "https://api.travis-ci.org/builds/195...".
Error: Unexpected end of input
SyntaxError: Failed to parse JSON from "https://api.travis-ci.org/builds/195...".
Error: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/travis/build/fastly/Tango/node_modules/travis-after-all/lib/travis-after-all.js:120:31)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
The project is on the private, hosted version of Travis. Perhaps there's a different API endpoint?

**Comment by jamesarosen** [comment]
https://docs.travis-ci.com/api suggests `api.travis-ci.com` for private projects. I'll try to work up a PR to support that.

**Comment by alrra** [comment]
>  I'll try to work up a PR to support that.

@jamesarosen That would be great! :)

--

Closing if favor of #6.
